[project]
name = "note"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "black>=26.1.0",
    "isort>=7.0.0",
    "jupyterlab>=4.5.1",
    "jupyterlab-code-formatter>=3.0.2",
    "jupyterlab-lsp>=5.2.0",
    "python-lsp-server[all]>=1.14.0",
]
