[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.2", features = [] }
serde_json = "1.0.145"
tauri-plugin-prevent-default = { version = "4.0.2", features = [
    "platform-windows",
] }
tauri-plugin-single-instance = "2.3.6"
tauri-plugin-os = "2.3.2"
tauri-plugin-opener = "2.5.2"
tauri-plugin-fs = "2.4.4"
tauri-plugin-sql = { version = "2.3.1", features = ["sqlite"] }

endpoint = { path = "../crates/endpoint" }
