[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.2", features = [] }
serde_json = "1.0.145"
tauri-plugin-prevent-default = { version = "3.0.3", features = [
    "platform-windows",
] }
tauri-plugin-single-instance = "2.3.6"
tauri-plugin-os = "2.3.2"
tauri-plugin-opener = "2.5.2"

thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive"] }
parking_lot = "0.12.5"
tokio = { version = "1.48.0", features = ["fs"] }
duckdb = { version = "1.4.1", features = ["bundled"] }
